language: csharp
dotnet: 2.1.802
mono: none
os:
  - linux
  - osx
solution: MathM-CI.sln
script:
  - dotnet restore
  - msbuild /p:Configuration=Release
  # - dotnet test
cache:
  directories:
    - artifacts
    - docs
