language: csharp
mono:
  - latest
os:
  - linux
  - osx
solution: MathM.sln
install:
  - nuget restore MathM.sln
script:
  - xbuild /p:Configuration=Release MathM.sln
#  - mono ./packages/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe --framework=mono-4.0 --labels=All --testlist=./ICSharpCode.SharpZipLib.Tests/PassingTests.txt --result=./Documentation/nunit3-test-results-travis.xml ./bin/Release/ICSharpCode.SharpZipLib.Tests.dll
#after_script:
#  - nuget pack Build/ICSharpCode.SharpZipLib.nuspec -BasePath Build -OutputDirectory bin/Release
cache:
  directories:
    - artifacts
    - docs
#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file:
#    - "bin/Release/ICSharpCode.SharpZipLib.nupkg"
#    - "Documentation/nunit3-test-results-travis.xml"
#  skip_cleanup: true
#  on:
#    tags: true
