language: csharp
dotnet: 2.1.802
mono: none
os:
  - linux
  - osx
solution: src\MathM-CI.csproj
script:
  - dotnet restore
  - msbuild /p:Configuration=Release src\MathM-CI.csproj
  # - dotnet test
cache:
  directories:
    - artifacts
    - docs
