# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
  - master

  # blacklist
  except:
  - gh-pages
  - coverity_scan

# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012

image: Visual Studio 2019

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# enable patching of *.csproj files
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to
                                  # account/project feeds for pull request builds

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  parallel: true
  project: MathM.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  # MSBuild verbosity level
  verbosity: minimal

#---------------------------------#
#        global handlers          #
#---------------------------------#

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

# Email
- provider: Email
  to:
    - mcneight+appveyor@gmail.com
  subject: Build {{status}}
  message: Version {{version}} {{commitId}} from {{branch}} {{status}} {{message}}
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
